#!/usr/bin/env python3
"""Interactive field tool for measuring mission.yaml waypoints from /Odometry."""

import argparse
import shutil
import threading
import time
from pathlib import Path

import rclpy
import yaml
from nav_msgs.msg import Odometry
from rclpy.executors import SingleThreadedExecutor
from rclpy.node import Node
from rclpy.qos import QoSProfile, ReliabilityPolicy


def default_mission_path():
    return Path(__file__).resolve().parents[1] / "src/top_launch_pkg/config/mission.yaml"


def default_output_path():
    stamp = time.strftime("%Y%m%d_%H%M%S")
    return Path("/tmp") / f"mission_measured_{stamp}.yaml"


def rounded(value):
    return round(float(value), 3)


class OdomProbe(Node):
    def __init__(self, odom_topic):
        super().__init__("mission_waypoint_measure")
        self.latest = None
        self.latest_wall_time = None
        qos = QoSProfile(depth=20, reliability=ReliabilityPolicy.BEST_EFFORT)
        self.create_subscription(Odometry, odom_topic, self.on_odom, qos)
        self.get_logger().info(f"Listening odometry on {odom_topic}")

    def on_odom(self, msg):
        self.latest = msg
        self.latest_wall_time = time.monotonic()

    def current_pose(self, max_age):
        if self.latest is None:
            raise RuntimeError("no odometry received yet")
        age = time.monotonic() - self.latest_wall_time
        if age > max_age:
            raise RuntimeError(f"latest odometry is stale ({age:.2f}s > {max_age:.2f}s)")
        p = self.latest.pose.pose.position
        return rounded(p.x), rounded(p.y), rounded(p.z), age


class MissionRecorder:
    def __init__(self, mission_path, output_path, in_place, append_existing):
        self.mission_path = Path(mission_path)
        self.output_path = Path(output_path)
        self.in_place = in_place
        self.doc = self.load_base_doc()
        self.waypoints = []
        if append_existing:
            self.waypoints.extend(self.doc.get("waypoints") or [])

    def load_base_doc(self):
        if not self.mission_path.exists():
            return {"default_tolerance": {"xy": 0.35, "z": 0.25}, "waypoints": []}
        with self.mission_path.open("r", encoding="utf-8") as f:
            doc = yaml.safe_load(f) or {}
        if "default_tolerance" not in doc:
            doc["default_tolerance"] = {"xy": 0.35, "z": 0.25}
        return doc

    def add_waypoint(self, pos, fly_through=False, label=""):
        wp = {"pos": [rounded(pos[0]), rounded(pos[1]), rounded(pos[2])]}
        if fly_through:
            wp["fly_through"] = True
        if label:
            wp["label"] = label
        self.waypoints.append(wp)
        return wp

    def undo(self):
        if not self.waypoints:
            return None
        return self.waypoints.pop()

    def write(self):
        doc = {
            "default_tolerance": self.doc.get("default_tolerance", {"xy": 0.35, "z": 0.25}),
            "waypoints": self.waypoints,
        }
        target = self.mission_path if self.in_place else self.output_path
        target.parent.mkdir(parents=True, exist_ok=True)
        if self.in_place and target.exists():
            backup = target.with_suffix(target.suffix + f".bak_{time.strftime('%Y%m%d_%H%M%S')}")
            shutil.copy2(target, backup)
            print(f"[measure] backup: {backup}")
        with target.open("w", encoding="utf-8") as f:
            f.write("# Generated by scripts/measure_mission_waypoints.py\n")
            f.write("# Coordinates are ENU map-frame positions measured from odometry.\n\n")
            yaml.safe_dump(doc, f, allow_unicode=True, sort_keys=False)
        print(f"[measure] wrote {len(self.waypoints)} waypoints -> {target}")

    def print_list(self):
        if not self.waypoints:
            print("[measure] no waypoints recorded")
            return
        for idx, wp in enumerate(self.waypoints, start=1):
            pos = wp["pos"]
            mode = "fly" if wp.get("fly_through") else "normal"
            label = f"  {wp.get('label')}" if wp.get("label") else ""
            print(f"[{idx:02d}] {pos[0]:8.3f} {pos[1]:8.3f} {pos[2]:6.3f}  {mode}{label}")


def parse_manual(parts):
    if len(parts) < 4:
        raise ValueError("manual format: m x y z [f|n] [label...]")
    x, y, z = (float(parts[1]), float(parts[2]), float(parts[3]))
    fly = False
    label_start = 4
    if len(parts) >= 5 and parts[4] in ("f", "fly", "fly_through", "n", "normal"):
        fly = parts[4] in ("f", "fly", "fly_through")
        label_start = 5
    label = " ".join(parts[label_start:]).strip()
    return (x, y, z), fly, label


def print_help():
    print(
        """
Commands:
  s                         show current odometry
  f [label]                 capture current pose as fly_through waypoint
  n [label]                 capture current pose as normal waypoint
  m x y z [f|n] [label]     add a manual ENU waypoint
  z <value>|auto            override captured Z, or return to odometry Z
  l                         list recorded waypoints
  u                         undo last waypoint
  w                         write output yaml
  h                         show this help
  q                         quit
""".strip()
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mission", default=str(default_mission_path()))
    parser.add_argument("--output", default=str(default_output_path()))
    parser.add_argument("--in-place", action="store_true",
                        help="write back to --mission, creating a timestamped backup first")
    parser.add_argument("--append-existing", action="store_true",
                        help="start from existing waypoints instead of replacing them in the output")
    parser.add_argument("--odom-topic", default="/Odometry")
    parser.add_argument("--max-odom-age", type=float, default=1.0)
    args = parser.parse_args()

    recorder = MissionRecorder(
        mission_path=args.mission,
        output_path=args.output,
        in_place=args.in_place,
        append_existing=args.append_existing,
    )

    rclpy.init()
    node = OdomProbe(args.odom_topic)
    executor = SingleThreadedExecutor()
    executor.add_node(node)
    spin_thread = threading.Thread(target=executor.spin, daemon=True)
    spin_thread.start()

    z_override = None
    print("[measure] mission:", args.mission)
    print("[measure] output :", args.mission if args.in_place else args.output)
    print_help()

    try:
        while rclpy.ok():
            try:
                raw = input("measure> ").strip()
            except EOFError:
                break
            if not raw:
                continue
            parts = raw.split()
            cmd = parts[0].lower()
            try:
                if cmd in ("q", "quit", "exit"):
                    break
                if cmd in ("h", "help", "?"):
                    print_help()
                elif cmd == "s":
                    x, y, z, age = node.current_pose(args.max_odom_age)
                    print(f"[measure] odom: x={x:.3f} y={y:.3f} z={z:.3f} age={age:.2f}s")
                elif cmd == "z":
                    if len(parts) != 2:
                        raise ValueError("usage: z <value>|auto")
                    z_override = None if parts[1] == "auto" else float(parts[1])
                    print(f"[measure] z override: {'auto' if z_override is None else z_override}")
                elif cmd in ("f", "fly", "n", "normal", "c", "capture"):
                    fly = cmd in ("f", "fly")
                    label = " ".join(parts[1:]).strip()
                    x, y, z, age = node.current_pose(args.max_odom_age)
                    if z_override is not None:
                        z = rounded(z_override)
                    wp = recorder.add_waypoint((x, y, z), fly, label)
                    print(f"[measure] captured #{len(recorder.waypoints)}: {wp}  odom_age={age:.2f}s")
                elif cmd == "m":
                    pos, fly, label = parse_manual(parts)
                    wp = recorder.add_waypoint(pos, fly, label)
                    print(f"[measure] added #{len(recorder.waypoints)}: {wp}")
                elif cmd == "l":
                    recorder.print_list()
                elif cmd == "u":
                    wp = recorder.undo()
                    print(f"[measure] undo: {wp}" if wp else "[measure] nothing to undo")
                elif cmd == "w":
                    recorder.write()
                else:
                    print(f"[measure] unknown command: {cmd}. Type h for help.")
            except (RuntimeError, ValueError) as exc:
                print(f"[measure] ERROR: {exc}")
    finally:
        executor.shutdown()
        node.destroy_node()
        rclpy.shutdown()
        spin_thread.join(timeout=1.0)


if __name__ == "__main__":
    main()
